### ISSUE TITLE
How to collect some one all answers into to mobi book?

### ISSUE THREAD

**Issue by suoba** [richardbeattie/Quora4Kindle#1]
Some great guys are so wonderful ,I want to read all what they write, of course with my kindle.
1.collect those answers 
2.send to my kindle

**Comment by r-bt** [comment]
This is something I been thinking of adding. You'd have a config file with a list of authors you follow and then it would automatically find their answers and send them to you. This does pose the problem however of recording what was the last answer that was sent to you but that could be easily solved I feel. 

While down the line I do hope to add the ability for the program itself to send the ebook directly to the kindle I'm focusing at the moment on making sure it can consistently get the answers from your feed. So it is necessary at the moment to email it yourself or use a program like calibre unfortunately.
